<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>cli</AssemblyName>
    <RootNamespace>Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConsoleAppFramework" />
    <PackageReference Include="ConsoleAppFramework.CliSchema" />
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="unit" />
    <InternalsVisibleTo Include="integration" />
  </ItemGroup>

</Project>
